[tool.poetry]
name = "lavague-qa"
version = "0.3.0"
description = "QA Automation with LaVague"
authors = ["lavague-ai"]
readme = "README.md"
license = "Apache-2.0"
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
  "Topic :: Software Development :: Libraries :: Application Frameworks",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "License :: OSI Approved :: Apache Software License",
]
keywords = ["QA", "testing", "automation", "cypress", "agents", "RAG", "selenium", "ai"]
homepage = "https://lavague.ai"
repository = "https://github.com/aabdullah-bos/LaVague.git"
documentation = "https://docs.lavague.ai/en/latest/"
packages = [{include = "lavague/"}]

[tool.poetry.dependencies]
python = "^3.11.9"
lavague-core = { git = "https://github.com/aabdullah-bos/LaVague.git", branch = "feature/driver-generator-hook", subdirectory = "lavague-core" }
lavague-tests = { git = "https://github.com/aabdullah-bos/LaVague.git", branch = "feature/driver-generator-hook", subdirectory = "lavague-tests" }
lavague-drivers-selenium = { git = "https://github.com/aabdullah-bos/LaVague.git", branch = "feature/driver-generator-hook", subdirectory = "lavague-integrations/drivers/lavague-drivers-selenium" }
lavague-contexts-openai = { git = "https://github.com/aabdullah-bos/LaVague.git", branch = "feature/driver-generator-hook", subdirectory = "lavague-integrations/contexts/lavague-contexts-openai" }
llama-index = "0.10.56"
selenium = "^4.27.0"
pytest = "^8.3.4"
pytest-bdd = "^7.3.0"
pyyaml = "^6.0.2"
gherkin-official = "^28.0.0"
click = "^8.1.7"
yaspin = "^3.0.2"
python-dotenv = "^1.2.1"

[tool.poetry.scripts]
lavague-qa = "lavague.qa.cli:cli"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
